settings:
  title: 'ä¸¸å­æœåŠ¡çŠ¶æ€'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: shop-wanziwk-shop
    name: wanziwk.shop(å•†åŸ)
    description: 'å°å°ç½‘è¯¾ï¼ç¨³å®šé«˜åˆ†!'
    url: 'https://shop.wanziwk.shop/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

    
  - id: wanziwk-cn # unique identifier
    name: wanziwk.cn(åå°)
    description: 'èµšç‚¹å°é’±ğŸ˜­' # default=empty
    url: 'https://wanziwk.cn/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: chat-wanziwk-cn
    name: wanziwk.cn(ChatGpt)
    description: 'æœ‰ç‚¹å‚»çš„AIæœåŠ¡'
    url: 'https://chat.wanziwk.cn/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
